server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://39.106.154.21:3306/car_demo?useUnicode=true&characterEncoding=utf-8
    username: wsj
    password: wsj666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB